# Main application
web:
  container_name: labory.web
  build: .
  command: bash ./start.sh
  volumes:
    - .:/app
  environment:
    RAILS_ENV: development
  ports:
    - "80:3000"
  links:
    - db
    - redis
  volumes_from:
    - bundle_store

# Database
db:
  container_name: labory.db
  image: postgres:9.5
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  ports:
    - "5432:5432"
  volumes_from:
    - db_store

# Redis
redis:
  container_name: labory.redis
  image: redis
  ports:
   - "6379:6379"
  volumes_from:
    - redis_store
  #flag: appendonly yes

# Data-only container for bundler data
# docker volume create labory.bundle_store
bundle_store:
  container_name: labory.bundle_store
  image: cogniteev/echo
  command: echo 'Data Container for Bundler'
  volumes:
    - labory.bundle_store:/usr/local/bundle

# Data-only container for database data
# docker volume create labory.db_store
db_store:
  container_name: labory.db_store
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - labory.db_store:/var/lib/postgresql/data

# Data-only container for redis data
# docker volume create labory.redis_store
redis_store:
  container_name: labory.redis_store
  image: cogniteev/echo
  command: echo 'Data Container for Redis'
  volumes:
    - labory.redis_store:/data
