# Main application
web:
  container_name: labory.web
  build: .
  dockerfile: Dockerfile.dev
  command: bash ./start.sh
  volumes:
    - .:/app
  env_file:
    - .env.development
  ports:
    - "80:3000"
  links:
    - db
    - redis
    - mailcatcher
  volumes_from:
    - bundle_store
  log_opt:
    max-size: "100k" # 100kb
    max-file: "20" # 20 lines

# Database
db:
  container_name: labory.db
  image: postgres:9.5
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  ports:
    - "5432:5432"
  volumes_from:
    - db_store
  log_driver: none

# Redis
redis:
  container_name: labory.redis
  image: redis
  ports:
   - "6379:6379"
  volumes_from:
    - redis_store
  #flag: appendonly yes
  log_driver: none

# Mailcatcher
mailcatcher:
  container_name: labory.mailcatcher
  image: tophfr/mailcatcher
  ports:
    - "1080:80"
    - "25:25"
  log_driver: none

# Sidekiq
sidekiq:
  container_name: labory.sidekiq
  build: .
  command: bundle exec sidekiq -C ./config/sidekiq-dev.yml
  volumes:
    - .:/app
  env_file:
    - .env.development
  links:
    - db
    - redis
    - mailcatcher
  volumes_from:
    - bundle_store
  log_driver: none

# Data-only container for bundler data
# docker volume create labory.bundle_store
bundle_store:
  container_name: labory.bundle_store
  image: cogniteev/echo
  command: echo 'Data Container for Bundler'
  volumes:
    - labory.bundle_store:/usr/local/bundle
  log_driver: none

# Data-only container for database data
# docker volume create labory.db_store
db_store:
  container_name: labory.db_store
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - labory.db_store:/var/lib/postgresql/data
  log_driver: none

# Data-only container for redis data
# docker volume create labory.redis_store
redis_store:
  container_name: labory.redis_store
  image: cogniteev/echo
  command: echo 'Data Container for Redis'
  volumes:
    - labory.redis_store:/data
  log_driver: none
